apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nacos-test.fullname" . }}
  labels:
    {{- include "nacos-test.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "nacos-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "nacos-test.selectorLabels" . | nindent 8 }}
        {{- with .Values.extraLable }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nacos-test.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "nacos-test.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ include "nacos-test.tag" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: default
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            {{- toYaml .Values.envVars | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.configmap.enabled }}
          volumeMounts:
          {{- with .Values.configmap }}
          {{- range $file := .configFile }}
            - name: config-volume
              mountPath: {{ $.Values.configmap.mountPath | trimSuffix "/" }}{{ cat "/" $file| nospace}}
              subPath: {{ $file | quote }}
          {{- end }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "nacos-test.fullname" . }}-config
            items:
            {{- range .Values.configmap.configFile }}
            - key: {{ . | quote }}
              path: {{ . | quote }}
            {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
