mysql:
  annotations: {}
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  service:
    port: 3306
#  rootPassword: root
#  database: nacos_devtest
#  user: nacos
#  password: nacos
  image:
    pullPolicy: IfNotPresent
    repository: harbor.cicconline.com/paas/nacos-test-mysql
    tag: 0.0.1
  classParameters: {}
  persistence:
    enabled: false
    existingClaim: nacos-test-mysql-data
    #existingClaim:
    claim:
      name: nacos-test-mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5G
        storageClassName: nfs-client
