{{- if ne .Values.global.mode "quickstart" }}
apiVersion: v1
kind: Service
metadata:
  name: nacos-test-mysql
  labels:
    name: nacos-test-mysql
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: nacos-test-mysql
      protocol: TCP
      name: nacos-test-mysql
  selector:
    name: nacos-test-mysql
{{- end }}
